name: CI

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby: ["2.6", "2.7", "3.0", "3.1"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: StandardRb check
      run: bundle exec standardrb

    - name: Run tests
      run: bundle exec rake
